--------------------------------------------------------
--  File created - Sunday-June-09-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BRANCHOVERRIDESEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BRANCHOVERRIDESEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence BRANCHSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BRANCHSEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 100000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence CATEGORYSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CATEGORYSEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 100000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence CWPRICINGRECORDSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CWPRICINGRECORDSEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence DESTINATIONSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DESTINATIONSEQ"  MINVALUE 4406 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 4406 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence DISTRICTSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DISTRICTSEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence MARKETSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MARKETSEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 100000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence MYPRICINGSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MYPRICINGSEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence NEWFREIGHTRATESEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NEWFREIGHTRATESEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence NEWLISTANDMULTIPLIERSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NEWLISTANDMULTIPLIERSEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence NEWPPTSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NEWPPTSEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence OGNTODSTFREIGHTRATESEQ
--------------------------------------------------------

   CREATE SEQUENCE  "OGNTODSTFREIGHTRATESEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence OGNTOSTATEFREIGHTRATESEQ
--------------------------------------------------------

   CREATE SEQUENCE  "OGNTOSTATEFREIGHTRATESEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence ORIGINATIONSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ORIGINATIONSEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence PRICINGADJUSTMENTSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRICINGADJUSTMENTSEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence PRICINGRECORDSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRICINGRECORDSEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence PRODUCTSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRODUCTSEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 100000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence PRODUCTTYPESEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRODUCTTYPESEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence REGIONSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REGIONSEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence ROLESEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ROLESEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence SHIPPOINTSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SHIPPOINTSEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 100000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence STATESEQ
--------------------------------------------------------

   CREATE SEQUENCE  "STATESEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence USERFILTERRECORDSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USERFILTERRECORDSEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence USERSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USERSEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence VENDORSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VENDORSEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 100000 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Table BRANCH
--------------------------------------------------------

  CREATE TABLE "BRANCH" 
   (	"ID" NUMBER(19,0), 
	"BRANCHNUMBER" VARCHAR2(20 BYTE), 
	"PROFITCENTER" VARCHAR2(50 BYTE), 
	"TRILOGONNAME" VARCHAR2(20 BYTE), 
	"CREATION_USER" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_USER" VARCHAR2(20 BYTE), 
	"MODIFICATION_DATE" TIMESTAMP (6), 
	"MARKET_ID" NUMBER(19,0), 
	"MACHINENAME" VARCHAR2(45 BYTE), 
	"PHONENUMBER" VARCHAR2(45 BYTE), 
	"FAXNUMBER" VARCHAR2(45 BYTE), 
	"REGION_ID" NUMBER(19,0), 
	"DISTRICT_ID" NUMBER(19,0), 
	"CONTACTNAME" VARCHAR2(45 BYTE), 
	"GENERALMANAGERNAME" VARCHAR2(45 BYTE), 
	"ADDRESS1" VARCHAR2(45 BYTE), 
	"ADDRESS2" VARCHAR2(45 BYTE), 
	"CITY" VARCHAR2(45 BYTE), 
	"STATE_ID" NUMBER(19,0), 
	"ZIPCODE" VARCHAR2(45 BYTE), 
	"MINIMALALLOWEDPRICE" NUMBER(20,0), 
	"MINIMALALLOWEDFREIGHTRATE" NUMBER(20,0)
   ) ;

--------------------------------------------------------
--  DDL for Table BRANCHOVERRIDE
--------------------------------------------------------

  CREATE TABLE "BRANCHOVERRIDE" 
   (	"ID" NUMBER(19,0), 
	"START_DATE" TIMESTAMP (6), 
	"CREATION_USER" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_USER" VARCHAR2(20 BYTE), 
	"MODIFICATION_DATE" TIMESTAMP (6), 
	"END_DATE" TIMESTAMP (6), 
	"VALUE" DECIMAL(20,2), 
	"RECORDTYPENAME" VARCHAR2(45 BYTE), 
	"RECORD_ID" NUMBER(19,0), 
	"BRANCH_ID" NUMBER(19,0), 
	"PRICINGADJUSTMENTCOL" VARCHAR2(200 BYTE)
   ) ;

--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "CATEGORY" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"CREATION_USER" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_USER" VARCHAR2(20 BYTE), 
	"MODIFICATION_DATE" TIMESTAMP (6), 
	"BRANCH_ID" NUMBER(19,0)
   ) ;

--------------------------------------------------------
--  DDL for Table CWPRICINGRECORD
--------------------------------------------------------

  CREATE TABLE "CWPRICINGRECORD" 
   (	"ID" NUMBER(19,0), 
	"INITIALLISTPRICE" NUMBER(20,2), 
	"SHIPPOINT_ID" NUMBER(19,0), 
	"PRODUCT" NUMBER(19,0), 
	"INITIALMULTIPLIER" NUMBER(20,4)
   ) ;

--------------------------------------------------------
--  DDL for Table DESTINATION
--------------------------------------------------------

  CREATE TABLE "DESTINATION" 
   (	"ID" NUMBER(19,0), 
	"BR" VARCHAR2(20 BYTE), 
	"ZIPCODE" VARCHAR2(45 BYTE), 
	"CREATION_USER" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_USER" VARCHAR2(20 BYTE), 
	"MODIFICATION_DATE" TIMESTAMP (6), 
	"STATE_ID" NUMBER(19,0), 
	"BRLOCATION" VARCHAR2(45 BYTE)
   ) ;

--------------------------------------------------------
--  DDL for Table DISTRICT
--------------------------------------------------------

  CREATE TABLE "DISTRICT" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(45 BYTE)
   ) ;

--------------------------------------------------------
--  DDL for Table MARKET
--------------------------------------------------------

  CREATE TABLE "MARKET" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"CREATION_USER" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_USER" VARCHAR2(20 BYTE), 
	"MODIFICATION_DATE" TIMESTAMP (6)
   ) ;

--------------------------------------------------------
--  DDL for Table MYPRICING
--------------------------------------------------------

  CREATE TABLE "MYPRICING" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"PROGRESS" BINARY_DOUBLE, 
	"CREATION_USER" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_USER" VARCHAR2(20 BYTE), 
	"MODIFICATION_DATE" TIMESTAMP (6), 
	"STATUS" NUMBER(11,0), 
	"PRICERECORD" NUMBER(19,0), 
	"CWPRICERECORD" NUMBER(19,0), 
	"CRITERIA" NUMBER(19,0),
	"BRANCHID" NUMBER(19,0),
	"RELATEDVALUEID" NUMBER(19,0)
   ) ;

--------------------------------------------------------
--  DDL for Table NEWFREIGHTRATE
--------------------------------------------------------

  CREATE TABLE "NEWFREIGHTRATE" 
   (	"ID" NUMBER(19,0), 
	"START_DATE" TIMESTAMP (6), 
	"CREATION_USER" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_USER" VARCHAR2(20 BYTE), 
	"MODIFICATION_DATE" TIMESTAMP (6), 
	"END_DATE" TIMESTAMP (6), 
	"VALUE" DECIMAL(20,2), 
	"RECORDTYPENAME" VARCHAR2(45 BYTE), 
	"RECORD_ID" NUMBER(19,0), 
	"BRANCH_ID" NUMBER(19,0), 
	"PRICINGADJUSTMENTCOL" VARCHAR2(200 BYTE)
   ) ;

--------------------------------------------------------
--  DDL for Table NEWLISTANDMULTIPLIER
--------------------------------------------------------

  CREATE TABLE "NEWLISTANDMULTIPLIER" 
   (	"ID" NUMBER(19,0), 
	"START_DATE" TIMESTAMP (6), 
	"CREATION_USER" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_USER" VARCHAR2(20 BYTE), 
	"MODIFICATION_DATE" TIMESTAMP (6), 
	"END_DATE" TIMESTAMP (6), 
	"LISTPRICE" NUMBER(20,2), 
	"RECORD" NUMBER(19,0), 
	"MULTIPLIER" NUMBER(20,4), 
	"PRICINGADJUSTMENTCOL" VARCHAR2(200 BYTE)
   ) ;

--------------------------------------------------------
--  DDL for Table NEWPPT
--------------------------------------------------------

  CREATE TABLE "NEWPPT" 
   (	"ID" NUMBER(19,0), 
	"START_DATE" TIMESTAMP (6), 
	"CREATION_USER" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_USER" VARCHAR2(20 BYTE), 
	"MODIFICATION_DATE" TIMESTAMP (6), 
	"END_DATE" TIMESTAMP (6), 
	"VALUE" NUMBER(20,0), 
	"RECORD" NUMBER(19,0), 
	"PRICINGADJUSTMENTCOL" VARCHAR2(200 BYTE)
   ) ;

--------------------------------------------------------
--  DDL for Table OGNTODSTFREIGHTRATE
--------------------------------------------------------

  CREATE TABLE "OGNTODSTFREIGHTRATE" 
   (	"ID" NUMBER(19,0), 
	"FREIGHTRATE" BINARY_DOUBLE, 
	"CREATION_USER" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_USER" VARCHAR2(20 BYTE), 
	"MODIFICATION_DATE" TIMESTAMP (6), 
	"DESTINATION" NUMBER(19,0), 
	"ORIGINATION_ID" NUMBER(19,0), 
	"FSC" BINARY_DOUBLE, 
	"RATE" BINARY_DOUBLE, 
	"MILEAGE" BINARY_DOUBLE
   ) ;

--------------------------------------------------------
--  DDL for Table ORIGINATION
--------------------------------------------------------

  CREATE TABLE "ORIGINATION" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"ZIPCODE" VARCHAR2(45 BYTE), 
	"CREATION_USER" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_USER" VARCHAR2(20 BYTE), 
	"MODIFICATION_DATE" TIMESTAMP (6), 
	"STATE_ID" NUMBER(19,0), 
	"PRODUCT_TYPE_ID" NUMBER(19,0)
   ) ;

--------------------------------------------------------
--  DDL for Table ORIGINATIONTOSTATEFREIGHTRATE
--------------------------------------------------------

  CREATE TABLE "ORIGINATIONTOSTATEFREIGHTRATE" 
   (	"ID" NUMBER(19,0), 
	"FREIGHTRATE" BINARY_DOUBLE, 
	"CREATION_USER" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_USER" VARCHAR2(20 BYTE), 
	"MODIFICATION_DATE" TIMESTAMP (6), 
	"STATE_ID" NUMBER(19,0), 
	"ORIGINATION_ID" NUMBER(19,0), 
	"FSC" BINARY_DOUBLE
   ) ;

--------------------------------------------------------
--  DDL for Table ORIGINATION_PRODUCTTYPE
--------------------------------------------------------

  CREATE TABLE "ORIGINATION_PRODUCTTYPE" 
   (	"ORIGINATION_ID" NUMBER(19,0), 
	"PRODUCT_ID" NUMBER(19,0)
   ) ;

--------------------------------------------------------
--  DDL for Table PRICINGADJUSTMENT
--------------------------------------------------------

  CREATE TABLE "PRICINGADJUSTMENT" 
   (	"ID" NUMBER(19,0), 
	"START_DATE" TIMESTAMP (6), 
	"CREATION_USER" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_USER" VARCHAR2(20 BYTE), 
	"MODIFICATION_DATE" TIMESTAMP (6), 
	"END_DATE" TIMESTAMP (6), 
	"VALUE" DECIMAL(20,2), 
	"RECORDTYPENAME" VARCHAR2(45 BYTE), 
	"RECORD_ID" NUMBER(19,0), 
	"BRANCH_ID" NUMBER(19,0), 
	"PRICINGADJUSTMENTCOL" VARCHAR2(200 BYTE)
   ) ;

--------------------------------------------------------
--  DDL for Table PRICINGRECORD
--------------------------------------------------------

  CREATE TABLE "PRICINGRECORD" 
   (	"ID" NUMBER(19,0), 
	"INITIALPPT" NUMBER(20,0), 
	"SHIPPOINT_ID" NUMBER(19,0), 
	"PRODUCT" NUMBER(19,0)
   ) ;

--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "PRODUCT" 
   (	"ID" NUMBER(19,0), 
	"PRODUCTCODE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"CREATION_USER" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_USER" VARCHAR2(20 BYTE), 
	"MODIFICATION_DATE" TIMESTAMP (6), 
	"ALTERNATECODE1" VARCHAR2(45 BYTE), 
	"HUNDREDWEIGHT" BINARY_DOUBLE, 
	"LISTPRICE" NUMBER(20,0), 
	"CATEGORY_ID" NUMBER(19,0), 
	"PRODUCT_TYPE_ID" NUMBER(19,0), 
	"SHIPPOINT_ID" NUMBER(19,0)
   ) ;

--------------------------------------------------------
--  DDL for Table PRODUCTTYPE
--------------------------------------------------------

  CREATE TABLE "PRODUCTTYPE" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"CREATION_USER" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_USER" VARCHAR2(20 BYTE), 
	"MODIFICATION_DATE" TIMESTAMP (6)
   ) ;

--------------------------------------------------------
--  DDL for Table REGION
--------------------------------------------------------

  CREATE TABLE "REGION" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(45 BYTE)
   ) ;

--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "ROLE" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"CREATION_USER" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_USER" VARCHAR2(20 BYTE), 
	"MODIFICATION_DATE" TIMESTAMP (6)
   ) ;

--------------------------------------------------------
--  DDL for Table SHIPPOINT
--------------------------------------------------------

  CREATE TABLE "SHIPPOINT" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	"ZIPCODE" VARCHAR2(45 BYTE), 
	"PHONENUMBER1" VARCHAR2(45 BYTE), 
	"PHONENUMBER2" VARCHAR2(45 BYTE), 
	"CONTACT1NAME" VARCHAR2(45 BYTE), 
	"CONTACT1EMAILADDRESS" VARCHAR2(45 BYTE), 
	"CONTACT2NAME" VARCHAR2(45 BYTE), 
	"CONTACT2EMAILADDRESS" VARCHAR2(45 BYTE), 
	"FAXNUMBER" VARCHAR2(45 BYTE), 
	"ISADC" NUMBER(1,0), 
	"VENDOR_ID" NUMBER(19,0), 
	"TYPE_ID" NUMBER(19,0)
   ) ;

--------------------------------------------------------
--  DDL for Table STATE
--------------------------------------------------------

  CREATE TABLE "STATE" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(45 BYTE), 
	"STATE_CODE" VARCHAR2(2 BYTE)
   ) ;

--------------------------------------------------------
--  DDL for Table STATE_LOOKUP
--------------------------------------------------------

  CREATE TABLE "STATE_LOOKUP" 
   (	"STATE_CODE" VARCHAR2(2 BYTE), 
	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(45 BYTE)
   ) ;

--------------------------------------------------------
--  DDL for Table USERFILTERRECORD
--------------------------------------------------------

  CREATE TABLE "USERFILTERRECORD" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"OWNER" NUMBER(19,0), 
	"TYPE" NUMBER(11,0), 
	"CREATION_USER" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_USER" VARCHAR2(20 BYTE), 
	"MODIFICATION_DATE" TIMESTAMP (6), 
	"READYTOEXPORT" NUMBER(1,0),
	"CRITERIAFLAG" NUMBER(1,0)
   ) ;

--------------------------------------------------------
--  DDL for Table USERFILTERRECORD_BRANCH
--------------------------------------------------------

  CREATE TABLE "USERFILTERRECORD_BRANCH" 
   (	"USERFILTERRECORD_ID" NUMBER(19,0), 
	"BRANCH_ID" NUMBER(19,0)
   ) ;

--------------------------------------------------------
--  DDL for Table USERFILTERRECORD_CATEGORY
--------------------------------------------------------

  CREATE TABLE "USERFILTERRECORD_CATEGORY" 
   (	"USERFILTERRECORD_ID" NUMBER(19,0), 
	"CATEGORY_ID" NUMBER(19,0)
   ) ;

--------------------------------------------------------
--  DDL for Table USERFILTERRECORD_MARKET
--------------------------------------------------------

  CREATE TABLE "USERFILTERRECORD_MARKET" 
   (	"USERFILTERRECORD_ID" NUMBER(19,0), 
	"MARKET_ID" NUMBER(19,0)
   ) ;

--------------------------------------------------------
--  DDL for Table USERFILTERRECORD_PRODUCTTYPE
--------------------------------------------------------

  CREATE TABLE "USERFILTERRECORD_PRODUCTTYPE" 
   (	"USERFILTERRECORD_ID" NUMBER(19,0), 
	"PRODUCTTYPE_ID" NUMBER(19,0)
   ) ;

--------------------------------------------------------
--  DDL for Table USERFILTERRECORD_SHIPPOINT
--------------------------------------------------------

  CREATE TABLE "USERFILTERRECORD_SHIPPOINT" 
   (	"USERFILTERRECORD_ID" NUMBER(19,0), 
	"SHIPPOINT_ID" NUMBER(19,0)
   ) ;

--------------------------------------------------------
--  DDL for Table USERFILTERRECORD_VENDOR
--------------------------------------------------------

  CREATE TABLE "USERFILTERRECORD_VENDOR" 
   (	"USERFILTERRECORD_ID" NUMBER(19,0), 
	"VENDOR_ID" NUMBER(19,0)
   ) ;

--------------------------------------------------------
--  DDL for Table USER_BRANCH
--------------------------------------------------------

  CREATE TABLE "USER_BRANCH" 
   (	"USER_ID" NUMBER(19,0), 
	"BRANCH_ID" NUMBER(19,0)
   ) ;

--------------------------------------------------------
--  DDL for Table USER_ROLE
--------------------------------------------------------

  CREATE TABLE "USER_ROLE" 
   (	"USER_ID" NUMBER(19,0), 
	"ROLE_ID" NUMBER(19,0)
   ) ;

--------------------------------------------------------
--  DDL for Table USER_TABLE
--------------------------------------------------------

  CREATE TABLE "USER_TABLE" 
   (	"ID" NUMBER(19,0), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"TOKEN" VARCHAR2(50 BYTE), 
	"CREATION_USER" VARCHAR2(20 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_USER" VARCHAR2(20 BYTE), 
	"MODIFICATION_DATE" TIMESTAMP (6), 
	"TOKEN_CREATION_DATE" TIMESTAMP (6), 
	"REMEMBER" NUMBER(1,0), 
	"FIRSTNAME" VARCHAR2(45 BYTE), 
	"LASTNAME" VARCHAR2(45 BYTE), 
	"TITLE" VARCHAR2(45 BYTE), 
	"PHONE" VARCHAR2(45 BYTE), 
	"MOBILE" VARCHAR2(45 BYTE), 
	"FAX" VARCHAR2(45 BYTE), 
	"EMAIL" VARCHAR2(45 BYTE), 
	"LAST_LOGIN_TS" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) ;

--------------------------------------------------------
--  DDL for Table VENDOR
--------------------------------------------------------

  CREATE TABLE "VENDOR" 
   (	"ID" NUMBER(19,0), 
	"VENDORNUMBER" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"ADDRESS1" VARCHAR2(20 BYTE), 
	"ADDRESS2" VARCHAR2(45 BYTE), 
	"CITY" VARCHAR2(45 BYTE), 
	"STATE_ID" NUMBER(19,0), 
	"ZIPCODE" VARCHAR2(45 BYTE), 
	"PHONENUMBER1" VARCHAR2(45 BYTE), 
	"PHONENUMBER2" VARCHAR2(45 BYTE), 
	"FAXNUMBER" VARCHAR2(45 BYTE), 
	"CONTACT1NAME" VARCHAR2(45 BYTE), 
	"CONTACT1EMAILADDRESS" VARCHAR2(45 BYTE), 
	"CONTACT2NAME" VARCHAR2(45 BYTE), 
	"CONTACT2EMAILADDRESS" VARCHAR2(45 BYTE)
   ) ;

--------------------------------------------------------
--  Constraints for Table USERFILTERRECORD_SHIPPOINT
--------------------------------------------------------

  ALTER TABLE "USERFILTERRECORD_SHIPPOINT" MODIFY ("USERFILTERRECORD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD_SHIPPOINT" MODIFY ("SHIPPOINT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD_SHIPPOINT" ADD PRIMARY KEY ("USERFILTERRECORD_ID", "SHIPPOINT_ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table USERFILTERRECORD_VENDOR
--------------------------------------------------------

  ALTER TABLE "USERFILTERRECORD_VENDOR" MODIFY ("USERFILTERRECORD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD_VENDOR" MODIFY ("VENDOR_ID" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD_VENDOR" ADD PRIMARY KEY ("USERFILTERRECORD_ID", "VENDOR_ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table SHIPPOINT
--------------------------------------------------------

  ALTER TABLE "SHIPPOINT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SHIPPOINT" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SHIPPOINT" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
 
  ALTER TABLE "SHIPPOINT" MODIFY ("ZIPCODE" NOT NULL ENABLE);
 
  ALTER TABLE "SHIPPOINT" MODIFY ("PHONENUMBER1" NOT NULL ENABLE);
 
  ALTER TABLE "SHIPPOINT" MODIFY ("PHONENUMBER2" NOT NULL ENABLE);
 
  ALTER TABLE "SHIPPOINT" MODIFY ("CONTACT1NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SHIPPOINT" MODIFY ("CONTACT1EMAILADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "SHIPPOINT" MODIFY ("CONTACT2NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SHIPPOINT" MODIFY ("CONTACT2EMAILADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "SHIPPOINT" MODIFY ("FAXNUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "SHIPPOINT" MODIFY ("ISADC" NOT NULL ENABLE);
 
  ALTER TABLE "SHIPPOINT" MODIFY ("VENDOR_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SHIPPOINT" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table USER_TABLE
--------------------------------------------------------

  ALTER TABLE "USER_TABLE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "USER_TABLE" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "USER_TABLE" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
--  ALTER TABLE "USER_TABLE" MODIFY ("TOKEN" NOT NULL ENABLE);
 
  ALTER TABLE "USER_TABLE" MODIFY ("CREATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "USER_TABLE" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "USER_TABLE" MODIFY ("MODIFICATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "USER_TABLE" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "USER_TABLE" MODIFY ("REMEMBER" NOT NULL ENABLE);
 
  ALTER TABLE "USER_TABLE" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
 
  ALTER TABLE "USER_TABLE" MODIFY ("LASTNAME" NOT NULL ENABLE);
 
  ALTER TABLE "USER_TABLE" MODIFY ("TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "USER_TABLE" MODIFY ("PHONE" NOT NULL ENABLE);
 
  ALTER TABLE "USER_TABLE" MODIFY ("MOBILE" NOT NULL ENABLE);
 
  ALTER TABLE "USER_TABLE" MODIFY ("FAX" NOT NULL ENABLE);
 
  ALTER TABLE "USER_TABLE" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "USER_TABLE" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table STATE
--------------------------------------------------------

  ALTER TABLE "STATE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "STATE" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "STATE" MODIFY ("STATE_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "STATE" ADD PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "STATE" ADD UNIQUE ("STATE_CODE") ENABLE;

--------------------------------------------------------
--  Constraints for Table NEWPPT
--------------------------------------------------------

  ALTER TABLE "NEWPPT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "NEWPPT" MODIFY ("START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "NEWPPT" MODIFY ("CREATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "NEWPPT" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "NEWPPT" MODIFY ("MODIFICATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "NEWPPT" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "NEWPPT" MODIFY ("END_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "NEWPPT" MODIFY ("VALUE" NOT NULL ENABLE);
 
  ALTER TABLE "NEWPPT" MODIFY ("RECORD" NOT NULL ENABLE);
 
  ALTER TABLE "NEWPPT" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table CWPRICINGRECORD
--------------------------------------------------------

  ALTER TABLE "CWPRICINGRECORD" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CWPRICINGRECORD" MODIFY ("INITIALLISTPRICE" NOT NULL ENABLE);
 
  ALTER TABLE "CWPRICINGRECORD" MODIFY ("SHIPPOINT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "CWPRICINGRECORD" MODIFY ("PRODUCT" NOT NULL ENABLE);
 
  ALTER TABLE "CWPRICINGRECORD" MODIFY ("INITIALMULTIPLIER" NOT NULL ENABLE);
 
  ALTER TABLE "CWPRICINGRECORD" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table USERFILTERRECORD_CATEGORY
--------------------------------------------------------

  ALTER TABLE "USERFILTERRECORD_CATEGORY" MODIFY ("USERFILTERRECORD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD_CATEGORY" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD_CATEGORY" ADD PRIMARY KEY ("USERFILTERRECORD_ID", "CATEGORY_ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table BRANCHOVERRIDE
--------------------------------------------------------

  ALTER TABLE "BRANCHOVERRIDE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCHOVERRIDE" MODIFY ("START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCHOVERRIDE" MODIFY ("CREATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCHOVERRIDE" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCHOVERRIDE" MODIFY ("MODIFICATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCHOVERRIDE" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCHOVERRIDE" MODIFY ("END_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCHOVERRIDE" MODIFY ("VALUE" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCHOVERRIDE" MODIFY ("RECORDTYPENAME" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCHOVERRIDE" MODIFY ("RECORD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCHOVERRIDE" MODIFY ("BRANCH_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCHOVERRIDE" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table BRANCH
--------------------------------------------------------

  ALTER TABLE "BRANCH" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("BRANCHNUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("PROFITCENTER" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("TRILOGONNAME" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("CREATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("MODIFICATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("MARKET_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("MACHINENAME" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("PHONENUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("FAXNUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("REGION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("DISTRICT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("CONTACTNAME" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("GENERALMANAGERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("ADDRESS1" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("ADDRESS2" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("CITY" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("STATE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" MODIFY ("ZIPCODE" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "PRODUCT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PRODUCT" MODIFY ("PRODUCTCODE" NOT NULL ENABLE);
 
  ALTER TABLE "PRODUCT" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
 
  ALTER TABLE "PRODUCT" MODIFY ("CREATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "PRODUCT" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "PRODUCT" MODIFY ("MODIFICATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "PRODUCT" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "PRODUCT" MODIFY ("ALTERNATECODE1" NOT NULL ENABLE);
 
  ALTER TABLE "PRODUCT" MODIFY ("HUNDREDWEIGHT" NOT NULL ENABLE);
 
  ALTER TABLE "PRODUCT" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PRODUCT" MODIFY ("PRODUCT_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PRODUCT" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table USER_BRANCH
--------------------------------------------------------

  ALTER TABLE "USER_BRANCH" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "USER_BRANCH" MODIFY ("BRANCH_ID" NOT NULL ENABLE);
 
  ALTER TABLE "USER_BRANCH" ADD PRIMARY KEY ("USER_ID", "BRANCH_ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table MARKET
--------------------------------------------------------

  ALTER TABLE "MARKET" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "MARKET" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "MARKET" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
 
  ALTER TABLE "MARKET" MODIFY ("CREATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "MARKET" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MARKET" MODIFY ("MODIFICATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "MARKET" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MARKET" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table STATE_LOOKUP
--------------------------------------------------------

  ALTER TABLE "STATE_LOOKUP" MODIFY ("STATE_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "STATE_LOOKUP" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "STATE_LOOKUP" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "STATE_LOOKUP" ADD PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "STATE_LOOKUP" ADD UNIQUE ("STATE_CODE") ENABLE;

--------------------------------------------------------
--  Constraints for Table VENDOR
--------------------------------------------------------

  ALTER TABLE "VENDOR" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "VENDOR" MODIFY ("VENDORNUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "VENDOR" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "VENDOR" MODIFY ("ADDRESS1" NOT NULL ENABLE);
 
  ALTER TABLE "VENDOR" MODIFY ("ADDRESS2" NOT NULL ENABLE);
 
  ALTER TABLE "VENDOR" MODIFY ("CITY" NOT NULL ENABLE);
 
  ALTER TABLE "VENDOR" MODIFY ("STATE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "VENDOR" MODIFY ("ZIPCODE" NOT NULL ENABLE);
 
  ALTER TABLE "VENDOR" MODIFY ("PHONENUMBER1" NOT NULL ENABLE);
 
  ALTER TABLE "VENDOR" MODIFY ("PHONENUMBER2" NOT NULL ENABLE);
 
  ALTER TABLE "VENDOR" MODIFY ("FAXNUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "VENDOR" MODIFY ("CONTACT1NAME" NOT NULL ENABLE);
 
  ALTER TABLE "VENDOR" MODIFY ("CONTACT1EMAILADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "VENDOR" MODIFY ("CONTACT2NAME" NOT NULL ENABLE);
 
  ALTER TABLE "VENDOR" MODIFY ("CONTACT2EMAILADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "VENDOR" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table OGNTODSTFREIGHTRATE
--------------------------------------------------------

  ALTER TABLE "OGNTODSTFREIGHTRATE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OGNTODSTFREIGHTRATE" MODIFY ("FREIGHTRATE" NOT NULL ENABLE);
 
  ALTER TABLE "OGNTODSTFREIGHTRATE" MODIFY ("CREATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "OGNTODSTFREIGHTRATE" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "OGNTODSTFREIGHTRATE" MODIFY ("MODIFICATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "OGNTODSTFREIGHTRATE" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "OGNTODSTFREIGHTRATE" MODIFY ("DESTINATION" NOT NULL ENABLE);
 
  ALTER TABLE "OGNTODSTFREIGHTRATE" MODIFY ("ORIGINATION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "OGNTODSTFREIGHTRATE" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table USER_ROLE
--------------------------------------------------------

  ALTER TABLE "USER_ROLE" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "USER_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "USER_ROLE" ADD PRIMARY KEY ("USER_ID", "ROLE_ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table NEWFREIGHTRATE
--------------------------------------------------------

  ALTER TABLE "NEWFREIGHTRATE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "NEWFREIGHTRATE" MODIFY ("START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "NEWFREIGHTRATE" MODIFY ("CREATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "NEWFREIGHTRATE" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "NEWFREIGHTRATE" MODIFY ("MODIFICATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "NEWFREIGHTRATE" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "NEWFREIGHTRATE" MODIFY ("END_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "NEWFREIGHTRATE" MODIFY ("VALUE" NOT NULL ENABLE);
 
  ALTER TABLE "NEWFREIGHTRATE" MODIFY ("RECORDTYPENAME" NOT NULL ENABLE);
 
  ALTER TABLE "NEWFREIGHTRATE" MODIFY ("RECORD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "NEWFREIGHTRATE" MODIFY ("BRANCH_ID" NOT NULL ENABLE);
 
  ALTER TABLE "NEWFREIGHTRATE" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table ORIGINATIONTOSTATEFREIGHTRATE
--------------------------------------------------------

  ALTER TABLE "ORIGINATIONTOSTATEFREIGHTRATE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "ORIGINATIONTOSTATEFREIGHTRATE" MODIFY ("FREIGHTRATE" NOT NULL ENABLE);
 
  ALTER TABLE "ORIGINATIONTOSTATEFREIGHTRATE" MODIFY ("CREATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "ORIGINATIONTOSTATEFREIGHTRATE" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "ORIGINATIONTOSTATEFREIGHTRATE" MODIFY ("MODIFICATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "ORIGINATIONTOSTATEFREIGHTRATE" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "ORIGINATIONTOSTATEFREIGHTRATE" MODIFY ("STATE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ORIGINATIONTOSTATEFREIGHTRATE" MODIFY ("ORIGINATION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ORIGINATIONTOSTATEFREIGHTRATE" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table DISTRICT
--------------------------------------------------------

  ALTER TABLE "DISTRICT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DISTRICT" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "DISTRICT" ADD PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "DISTRICT" ADD UNIQUE ("NAME") ENABLE;

--------------------------------------------------------
--  Constraints for Table DESTINATION
--------------------------------------------------------

  ALTER TABLE "DESTINATION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DESTINATION" MODIFY ("BR" NOT NULL ENABLE);
 
  ALTER TABLE "DESTINATION" MODIFY ("ZIPCODE" NOT NULL ENABLE);
 
  ALTER TABLE "DESTINATION" MODIFY ("CREATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "DESTINATION" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "DESTINATION" MODIFY ("MODIFICATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "DESTINATION" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "DESTINATION" MODIFY ("STATE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DESTINATION" MODIFY ("BRLOCATION" NOT NULL ENABLE);
 
  ALTER TABLE "DESTINATION" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table REGION
--------------------------------------------------------

  ALTER TABLE "REGION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "REGION" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "REGION" ADD PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "REGION" ADD UNIQUE ("NAME") ENABLE;

--------------------------------------------------------
--  Constraints for Table ORIGINATION
--------------------------------------------------------

  ALTER TABLE "ORIGINATION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "ORIGINATION" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "ORIGINATION" MODIFY ("ZIPCODE" NOT NULL ENABLE);
 
  ALTER TABLE "ORIGINATION" MODIFY ("CREATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "ORIGINATION" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "ORIGINATION" MODIFY ("MODIFICATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "ORIGINATION" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "ORIGINATION" MODIFY ("STATE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ORIGINATION" MODIFY ("PRODUCT_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ORIGINATION" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table PRICINGRECORD
--------------------------------------------------------

  ALTER TABLE "PRICINGRECORD" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PRICINGRECORD" MODIFY ("INITIALPPT" NOT NULL ENABLE);
 
  ALTER TABLE "PRICINGRECORD" MODIFY ("SHIPPOINT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PRICINGRECORD" MODIFY ("PRODUCT" NOT NULL ENABLE);
 
  ALTER TABLE "PRICINGRECORD" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "CATEGORY" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CATEGORY" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "CATEGORY" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
 
  ALTER TABLE "CATEGORY" MODIFY ("CREATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "CATEGORY" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "CATEGORY" MODIFY ("MODIFICATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "CATEGORY" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "CATEGORY" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table USERFILTERRECORD_PRODUCTTYPE
--------------------------------------------------------

  ALTER TABLE "USERFILTERRECORD_PRODUCTTYPE" MODIFY ("USERFILTERRECORD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD_PRODUCTTYPE" MODIFY ("PRODUCTTYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD_PRODUCTTYPE" ADD PRIMARY KEY ("USERFILTERRECORD_ID", "PRODUCTTYPE_ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table PRODUCTTYPE
--------------------------------------------------------

  ALTER TABLE "PRODUCTTYPE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PRODUCTTYPE" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "PRODUCTTYPE" MODIFY ("CREATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "PRODUCTTYPE" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "PRODUCTTYPE" MODIFY ("MODIFICATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "PRODUCTTYPE" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "PRODUCTTYPE" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table ORIGINATION_PRODUCTTYPE
--------------------------------------------------------

  ALTER TABLE "ORIGINATION_PRODUCTTYPE" MODIFY ("ORIGINATION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ORIGINATION_PRODUCTTYPE" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table USERFILTERRECORD_BRANCH
--------------------------------------------------------

  ALTER TABLE "USERFILTERRECORD_BRANCH" MODIFY ("USERFILTERRECORD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD_BRANCH" MODIFY ("BRANCH_ID" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD_BRANCH" ADD PRIMARY KEY ("USERFILTERRECORD_ID", "BRANCH_ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table USERFILTERRECORD
--------------------------------------------------------

  ALTER TABLE "USERFILTERRECORD" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD" MODIFY ("OWNER" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD" MODIFY ("TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD" MODIFY ("CREATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD" MODIFY ("MODIFICATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD" MODIFY ("READYTOEXPORT" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table NEWLISTANDMULTIPLIER
--------------------------------------------------------

  ALTER TABLE "NEWLISTANDMULTIPLIER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "NEWLISTANDMULTIPLIER" MODIFY ("START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "NEWLISTANDMULTIPLIER" MODIFY ("CREATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "NEWLISTANDMULTIPLIER" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "NEWLISTANDMULTIPLIER" MODIFY ("MODIFICATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "NEWLISTANDMULTIPLIER" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "NEWLISTANDMULTIPLIER" MODIFY ("END_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "NEWLISTANDMULTIPLIER" MODIFY ("LISTPRICE" NOT NULL ENABLE);
 
  ALTER TABLE "NEWLISTANDMULTIPLIER" MODIFY ("RECORD" NOT NULL ENABLE);
 
  ALTER TABLE "NEWLISTANDMULTIPLIER" MODIFY ("MULTIPLIER" NOT NULL ENABLE);
 
  ALTER TABLE "NEWLISTANDMULTIPLIER" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table MYPRICING
--------------------------------------------------------

  ALTER TABLE "MYPRICING" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "MYPRICING" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "MYPRICING" MODIFY ("PROGRESS" NOT NULL ENABLE);
 
  ALTER TABLE "MYPRICING" MODIFY ("CREATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "MYPRICING" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MYPRICING" MODIFY ("MODIFICATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "MYPRICING" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MYPRICING" MODIFY ("STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "MYPRICING" MODIFY ("CRITERIA" NOT NULL ENABLE);
 
  ALTER TABLE "MYPRICING" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "ROLE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "ROLE" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "ROLE" MODIFY ("CREATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "ROLE" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "ROLE" MODIFY ("MODIFICATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "ROLE" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "ROLE" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table PRICINGADJUSTMENT
--------------------------------------------------------

  ALTER TABLE "PRICINGADJUSTMENT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PRICINGADJUSTMENT" MODIFY ("START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "PRICINGADJUSTMENT" MODIFY ("CREATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "PRICINGADJUSTMENT" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "PRICINGADJUSTMENT" MODIFY ("MODIFICATION_USER" NOT NULL ENABLE);
 
  ALTER TABLE "PRICINGADJUSTMENT" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "PRICINGADJUSTMENT" MODIFY ("END_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "PRICINGADJUSTMENT" MODIFY ("VALUE" NOT NULL ENABLE);
 
  ALTER TABLE "PRICINGADJUSTMENT" MODIFY ("RECORDTYPENAME" NOT NULL ENABLE);
 
  ALTER TABLE "PRICINGADJUSTMENT" MODIFY ("RECORD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PRICINGADJUSTMENT" MODIFY ("BRANCH_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PRICINGADJUSTMENT" ADD PRIMARY KEY ("ID") ENABLE;

--------------------------------------------------------
--  Constraints for Table USERFILTERRECORD_MARKET
--------------------------------------------------------

  ALTER TABLE "USERFILTERRECORD_MARKET" MODIFY ("USERFILTERRECORD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD_MARKET" MODIFY ("MARKET_ID" NOT NULL ENABLE);
 
  ALTER TABLE "USERFILTERRECORD_MARKET" ADD PRIMARY KEY ("USERFILTERRECORD_ID", "MARKET_ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table BRANCH
--------------------------------------------------------

  ALTER TABLE "BRANCH" ADD CONSTRAINT "FK_BRANCH_DISTRICT" FOREIGN KEY ("DISTRICT_ID")
	  REFERENCES "DISTRICT" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "BRANCH" ADD CONSTRAINT "FK_BRANCH_MARKET" FOREIGN KEY ("MARKET_ID")
	  REFERENCES "MARKET" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "BRANCH" ADD CONSTRAINT "FK_BRANCH_REGION" FOREIGN KEY ("REGION_ID")
	  REFERENCES "REGION" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "BRANCH" ADD CONSTRAINT "FK_BRANCH_STATE" FOREIGN KEY ("STATE_ID")
	  REFERENCES "STATE" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table BRANCHOVERRIDE
--------------------------------------------------------

  ALTER TABLE "BRANCHOVERRIDE" ADD CONSTRAINT "FK_BRANCHOVERRIDE_BRANCH" FOREIGN KEY ("BRANCH_ID")
	  REFERENCES "BRANCH" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "CATEGORY" ADD CONSTRAINT "FK_CATEGORY_BRANCH" FOREIGN KEY ("BRANCH_ID")
	  REFERENCES "BRANCH" ("ID") ON DELETE SET NULL ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table CWPRICINGRECORD
--------------------------------------------------------

  ALTER TABLE "CWPRICINGRECORD" ADD CONSTRAINT "FK_CWPRICINGRECORD_PRODUCT" FOREIGN KEY ("PRODUCT")
	  REFERENCES "PRODUCT" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "CWPRICINGRECORD" ADD CONSTRAINT "FK_CWPRICINGRECORD_SHIPPOINT" FOREIGN KEY ("SHIPPOINT_ID")
	  REFERENCES "SHIPPOINT" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table DESTINATION
--------------------------------------------------------

  ALTER TABLE "DESTINATION" ADD CONSTRAINT "FK_DESTINATION_STATE" FOREIGN KEY ("STATE_ID")
	  REFERENCES "STATE" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table MYPRICING
--------------------------------------------------------

  ALTER TABLE "MYPRICING" ADD CONSTRAINT "FK_MYPRICING_CWPRICINGRECORD" FOREIGN KEY ("CWPRICERECORD")
	  REFERENCES "CWPRICINGRECORD" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "MYPRICING" ADD CONSTRAINT "FK_MYPRICING_PRICINGRECORD" FOREIGN KEY ("PRICERECORD")
	  REFERENCES "PRICINGRECORD" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "MYPRICING" ADD CONSTRAINT "FK_MYPRICING_USERFILTERRECORD" FOREIGN KEY ("CRITERIA")
	  REFERENCES "USERFILTERRECORD" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table NEWFREIGHTRATE
--------------------------------------------------------

  ALTER TABLE "NEWFREIGHTRATE" ADD CONSTRAINT "FK_NEWFREIGHTRATE_BRANCH" FOREIGN KEY ("BRANCH_ID")
	  REFERENCES "BRANCH" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table NEWLISTANDMULTIPLIER
--------------------------------------------------------

  ALTER TABLE "NEWLISTANDMULTIPLIER" ADD CONSTRAINT "FK_WLAM_CWPRICINGRECORD" FOREIGN KEY ("RECORD")
	  REFERENCES "CWPRICINGRECORD" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table NEWPPT
--------------------------------------------------------

  ALTER TABLE "NEWPPT" ADD CONSTRAINT "FK_NEWPPT_PRICINGRECORD" FOREIGN KEY ("RECORD")
	  REFERENCES "PRICINGRECORD" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table OGNTODSTFREIGHTRATE
--------------------------------------------------------

  ALTER TABLE "OGNTODSTFREIGHTRATE" ADD CONSTRAINT "FK_OGNTODSTFR_DESTINATION" FOREIGN KEY ("DESTINATION")
	  REFERENCES "DESTINATION" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "OGNTODSTFREIGHTRATE" ADD CONSTRAINT "FK_OGNTODSTFR_ORIGINATION" FOREIGN KEY ("ORIGINATION_ID")
	  REFERENCES "ORIGINATION" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table ORIGINATION
--------------------------------------------------------

  ALTER TABLE "ORIGINATION" ADD CONSTRAINT "FK_ORIGINATION_PRODUCTTYPE" FOREIGN KEY ("PRODUCT_TYPE_ID")
	  REFERENCES "PRODUCTTYPE" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "ORIGINATION" ADD CONSTRAINT "FK_ORIGINATION_STATE" FOREIGN KEY ("STATE_ID")
	  REFERENCES "STATE" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table ORIGINATIONTOSTATEFREIGHTRATE
--------------------------------------------------------

  ALTER TABLE "ORIGINATIONTOSTATEFREIGHTRATE" ADD CONSTRAINT "FK_OGNTOSTATEFR_ORIGINATION" FOREIGN KEY ("ORIGINATION_ID")
	  REFERENCES "ORIGINATION" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "ORIGINATIONTOSTATEFREIGHTRATE" ADD CONSTRAINT "FK_OGNTOSTATEFR_STATE" FOREIGN KEY ("STATE_ID")
	  REFERENCES "STATE" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table PRICINGADJUSTMENT
--------------------------------------------------------

  ALTER TABLE "PRICINGADJUSTMENT" ADD CONSTRAINT "FK_PRICINGADJUSTMENT_BRANCH" FOREIGN KEY ("BRANCH_ID")
	  REFERENCES "BRANCH" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table PRICINGRECORD
--------------------------------------------------------

  ALTER TABLE "PRICINGRECORD" ADD CONSTRAINT "FK_PRICINGRECORD_PRODUCT" FOREIGN KEY ("PRODUCT")
	  REFERENCES "PRODUCT" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "PRICINGRECORD" ADD CONSTRAINT "FK_PRICINGRECORD_SHIPPOINT" FOREIGN KEY ("SHIPPOINT_ID")
	  REFERENCES "SHIPPOINT" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_PRODUCT_CATEGORY" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "CATEGORY" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_PRODUCT_PRODUCTTYPE" FOREIGN KEY ("PRODUCT_TYPE_ID")
	  REFERENCES "PRODUCTTYPE" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_PRODUCT_SHIPPOINT" FOREIGN KEY ("SHIPPOINT_ID")
	  REFERENCES "SHIPPOINT" ("ID") ON DELETE SET NULL ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table SHIPPOINT
--------------------------------------------------------

  ALTER TABLE "SHIPPOINT" ADD CONSTRAINT "FK_SHIPPOINT_VENDOR" FOREIGN KEY ("VENDOR_ID")
	  REFERENCES "VENDOR" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table USERFILTERRECORD
--------------------------------------------------------

  ALTER TABLE "USERFILTERRECORD" ADD CONSTRAINT "FK_USERFILTERRECORD_USER" FOREIGN KEY ("OWNER")
	  REFERENCES "USER_TABLE" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table USERFILTERRECORD_BRANCH
--------------------------------------------------------

  ALTER TABLE "USERFILTERRECORD_BRANCH" ADD CONSTRAINT "FK_UFR_BRANCH_BRANCH" FOREIGN KEY ("BRANCH_ID")
	  REFERENCES "BRANCH" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "USERFILTERRECORD_BRANCH" ADD CONSTRAINT "FK_UFR_BRANCH_UFR" FOREIGN KEY ("USERFILTERRECORD_ID")
	  REFERENCES "USERFILTERRECORD" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table USERFILTERRECORD_CATEGORY
--------------------------------------------------------

  ALTER TABLE "USERFILTERRECORD_CATEGORY" ADD CONSTRAINT "FK_UFR_CATEGORY_CATEGORY" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "CATEGORY" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "USERFILTERRECORD_CATEGORY" ADD CONSTRAINT "FK_UFR_CATEGORY_UFR" FOREIGN KEY ("USERFILTERRECORD_ID")
	  REFERENCES "USERFILTERRECORD" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table USERFILTERRECORD_MARKET
--------------------------------------------------------

  ALTER TABLE "USERFILTERRECORD_MARKET" ADD CONSTRAINT "FK_UFR_MARKET_MARKET" FOREIGN KEY ("MARKET_ID")
	  REFERENCES "MARKET" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "USERFILTERRECORD_MARKET" ADD CONSTRAINT "FK_UFR_MARKET_UFR" FOREIGN KEY ("USERFILTERRECORD_ID")
	  REFERENCES "USERFILTERRECORD" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table USERFILTERRECORD_PRODUCTTYPE
--------------------------------------------------------

  ALTER TABLE "USERFILTERRECORD_PRODUCTTYPE" ADD CONSTRAINT "FK_UFR_PRODUCTTYPE_PRODUCTTYPE" FOREIGN KEY ("PRODUCTTYPE_ID")
	  REFERENCES "PRODUCTTYPE" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "USERFILTERRECORD_PRODUCTTYPE" ADD CONSTRAINT "FK_UFR_PRODUCTTYPE_UFR" FOREIGN KEY ("USERFILTERRECORD_ID")
	  REFERENCES "USERFILTERRECORD" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table USERFILTERRECORD_VENDOR
--------------------------------------------------------

  ALTER TABLE "USERFILTERRECORD_VENDOR" ADD CONSTRAINT "FK_UFR_VENDOR_UFR" FOREIGN KEY ("USERFILTERRECORD_ID")
	  REFERENCES "USERFILTERRECORD" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "USERFILTERRECORD_VENDOR" ADD CONSTRAINT "FK_UFR_VENDOR_VENDOR" FOREIGN KEY ("VENDOR_ID")
	  REFERENCES "VENDOR" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table USER_BRANCH
--------------------------------------------------------

  ALTER TABLE "USER_BRANCH" ADD CONSTRAINT "FK_USER_BRANCH_BRANCH" FOREIGN KEY ("BRANCH_ID")
	  REFERENCES "BRANCH" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "USER_BRANCH" ADD CONSTRAINT "FK_USER_BRANCH_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "USER_TABLE" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table USER_ROLE
--------------------------------------------------------

  ALTER TABLE "USER_ROLE" ADD CONSTRAINT "FK_USER_ROLE_ROLE" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "ROLE" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "USER_ROLE" ADD CONSTRAINT "FK_USER_ROLE_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "USER_TABLE" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table VENDOR
--------------------------------------------------------

  ALTER TABLE "VENDOR" ADD CONSTRAINT "FK_VENDOR_STATE" FOREIGN KEY ("STATE_ID")
	  REFERENCES "STATE" ("ID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  DDL for Table USERFILTERRECORD_PRODUCT
--------------------------------------------------------

CREATE TABLE "USERFILTERRECORD_PRODUCT" (
  "USERFILTERRECORD_ID" NUMBER(19,0), 
  "PRODUCT_ID" NUMBER(19,0)
);

--------------------------------------------------------
--  Constraints for Table USERFILTERRECORD_SHIPPOINT
--------------------------------------------------------

ALTER TABLE "USERFILTERRECORD_PRODUCT" MODIFY ("USERFILTERRECORD_ID" NOT NULL ENABLE);
ALTER TABLE "USERFILTERRECORD_PRODUCT" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
ALTER TABLE "USERFILTERRECORD_PRODUCT" ADD PRIMARY KEY ("USERFILTERRECORD_ID", "PRODUCT_ID") ENABLE;	  